# Generated by Django 5.0 on 2023-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('RUB', 'rub')], default=('USD', 'usd'), help_text='Выбор валюты для конвертации', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(help_text='Цена товара в центах', verbose_name='Цена'),
        ),
    ]
